function ASS=jxxh(T,nx,ny,lx,ly)
dd=reshape(T,ny,nx);
[ddkb,Nkb,NxL,NyL,NxR,NyR]=kuobian(dd,nx,ny);
u=fftshift((1:Nkb)-Nkb/2-1);
u=-2*pi.*(u)./((Nkb-1)*lx);
v=fftshift((1:Nkb)-Nkb/2-1);
v=-2*pi.*(v)./((Nkb-1)*ly);
[uu,vv]=meshgrid(u,v);
w=sqrt(uu.^2+vv.^2);
Fddkb=fft2(ddkb);
[ddkbx,ddkby]=gradient(ddkb);
%x
ddx=ddkbx(NyL+1:NyL+ny,NxL+1:NxL+nx)/lx;
%y
ddy=ddkby(NyL+1:NyL+ny,NxL+1:NxL+nx)/ly;
%z
Fddkbz=w.*Fddkb;
ddkbz=real(ifft2(Fddkbz));
ddz=ddkbz(NyL+1:NyL+ny,NxL+1:NxL+nx);
%%
ASS=sqrt(ddx.^2+ddy.^2+ddz.^2);
end
